/*
 *  This file (SQL.java) is a part of project XConomy
 *  Copyright (C) YiC and contributors
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 *  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 *  for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
package me.yic.xconomy.data.sql;

import me.yic.xconomy.XConomy;
import me.yic.xconomy.XConomyLoad;
import me.yic.xconomy.data.BalanceMutationResult;
import me.yic.xconomy.data.BalanceTransferResult;
import me.yic.xconomy.data.DataFormat;
import me.yic.xconomy.data.DataLink;
import me.yic.xconomy.data.DataMigration;
import me.yic.xconomy.data.GetUUID;
import me.yic.xconomy.data.caches.Cache;
import me.yic.xconomy.data.caches.CacheNonPlayer;
import me.yic.xconomy.data.syncdata.PlayerData;
import me.yic.xconomy.info.RecordInfo;
import me.yic.xconomy.utils.DatabaseConnection;
import me.yic.xconomy.utils.UUIDMode;

import java.math.BigDecimal;
import java.sql.*;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.UUID;

public class SQL {

    private static final Object WRITE_LOCK = new Object();

    public static String tableName = "xconomy";
    public static String tableNonPlayerName = "xconomynon";
    public static String tableRecordName = "xconomyrecord";
    public static String tableUUIDName = "xconomyuuid";
    public static String tableLoginName = "xconomylogin";
    public final static DatabaseConnection database = new DatabaseConnection();
    static final String encoding = XConomyLoad.DConfig.ENCODING;

    public static boolean con() {
        return database.setGlobalConnection();
    }

    public static void close() {
        database.close();
    }

    public static void getwaittimeout() {
        if (XConomyLoad.DConfig.isMySQL()) {
            try {
                Connection connection = database.getConnectionAndCheck();

                String query = "show variables like 'wait_timeout'";

                PreparedStatement statement = connection.prepareStatement(query);

                ResultSet rs = statement.executeQuery();
                if (rs.next()) {
                    int waittime = rs.getInt(2);
                    if (waittime > 50) {
                        database.waittimeout = waittime - 30;
                    }

                }

                rs.close();
                statement.close();
                database.closeHikariConnection(connection);

            } catch (SQLException ignored) {
                XConomy.getInstance().logger(null, 1, "Get 'wait_timeout' error");
            }
        }

        database.setHikariValidationTimeout();

    }

    public static boolean createTable() {
        Connection connection = database.getConnectionAndCheck();
        if (connection == null) {
            return false;
        }
        try (Statement statement = connection.createStatement()) {
            boolean postgres = XConomyLoad.DConfig.isPostgreSQL();
            String textType = postgres ? "VARCHAR(50)" : "varchar(50)";
            String balanceType = postgres ? "DOUBLE PRECISION" : "double(20,2)";
            String intType = postgres ? "INTEGER" : "int(5)";
            String query1 = "CREATE TABLE IF NOT EXISTS " + tableName
                    + " (UID " + textType + " NOT NULL, player " + textType + " NOT NULL, balance "
                    + balanceType + " NOT NULL, hidden " + intType + " NOT NULL, PRIMARY KEY (UID))";
            String query2 = "CREATE TABLE IF NOT EXISTS " + tableNonPlayerName
                    + " (account " + textType + " NOT NULL, balance " + balanceType + " NOT NULL, PRIMARY KEY (account))";
            String query5 = "CREATE TABLE IF NOT EXISTS " + tableUUIDName
                    + " (UUID " + textType + " NOT NULL, DUUID " + textType + " NOT NULL, PRIMARY KEY (UUID))";

            statement.executeUpdate(query1);
            if (DataLink.hasnonplayerplugin || XConomyLoad.Config.NON_PLAYER_ACCOUNT) {
                statement.executeUpdate(query2);
            }
            if (XConomyLoad.Config.UUIDMODE.equals(UUIDMode.SEMIONLINE)) {
                statement.executeUpdate(query5);
            }
            if (XConomyLoad.DConfig.isRemoteDatabase() && XConomyLoad.Config.TRANSACTION_RECORD) {
                String idType = postgres ? "BIGINT GENERATED BY DEFAULT AS IDENTITY" : "BIGINT AUTO_INCREMENT";
                String dateType = postgres ? "TIMESTAMP" : "DATETIME";
                String query3 = "CREATE TABLE IF NOT EXISTS " + tableRecordName
                        + " (id " + idType + " PRIMARY KEY, type " + textType + " NOT NULL, uid " + textType + " NOT NULL,"
                        + " player " + textType + " NOT NULL, balance " + balanceType + ", amount " + balanceType + " NOT NULL,"
                        + " operation " + textType + " NOT NULL, command VARCHAR(255) NOT NULL, comment VARCHAR(255) NOT NULL,"
                        + " datetime " + dateType + " NOT NULL, from_uid " + textType + ", to_uid " + textType
                        + ", transaction_type VARCHAR(20), server_id " + textType + ", trace_id " + textType
                        + ", parent_transaction_id BIGINT)";
                statement.executeUpdate(query3);
                createRecordIndexes(statement, postgres);
                if (XConomyLoad.Config.PAY_TIPS) {
                    statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + tableLoginName
                            + " (UUID " + textType + " NOT NULL, last_time " + dateType + " NOT NULL, PRIMARY KEY (UUID))");
                }
            }
            return true;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        } finally {
            database.closeHikariConnection(connection);
        }
    }

    private static void createRecordIndexes(Statement statement, boolean postgres) throws SQLException {
        String[] indexes = {"uid", "from_uid", "to_uid", "datetime", "transaction_type", "trace_id", "parent_transaction_id"};
        for (String column : indexes) {
            String indexName = postgres
                    ? "idx_" + Integer.toHexString(tableRecordName.hashCode()) + "_" + column
                    : "idx_" + column;
            String sql = postgres
                    ? "CREATE INDEX IF NOT EXISTS " + indexName + " ON " + tableRecordName + " (" + column + ")"
                    : "CREATE INDEX " + indexName + " ON " + tableRecordName + " (" + column + ")";
            try {
                statement.executeUpdate(sql);
            } catch (SQLException ignored) {
                // MySQL may already have the index from an earlier schema version.
            }
        }
    }

    /**
     * Upgrade existing record table to add tracking fields
     */
    public static void upgradeRecordTableForTracking() {
        Connection connection = database.getConnectionAndCheck();
        if (connection == null) {
            return;
        }
        try (Statement statement = connection.createStatement()) {
            DatabaseMetaData metaData = connection.getMetaData();
            String[][] columns = {
                    {"from_uid", "VARCHAR(50)"}, {"to_uid", "VARCHAR(50)"},
                    {"transaction_type", "VARCHAR(20)"}, {"server_id", "VARCHAR(50)"},
                    {"trace_id", "VARCHAR(50)"}, {"parent_transaction_id", "BIGINT"}
            };
            boolean upgraded = false;
            for (String[] column : columns) {
                if (!columnExists(metaData, tableRecordName, column[0])) {
                    statement.executeUpdate("ALTER TABLE " + tableRecordName + " ADD COLUMN " + column[0] + " " + column[1]);
                    upgraded = true;
                }
            }
            createRecordIndexes(statement, XConomyLoad.DConfig.isPostgreSQL());
            if (upgraded) {
                XConomy.getInstance().logger(null, 0, "Upgraded transaction record table for tracking");
            }
        } catch (SQLException e) {
            XConomy.getInstance().logger(null, 1, "Error upgrading record table");
            e.printStackTrace();
        } finally {
            database.closeHikariConnection(connection);
        }
    }

    private static boolean columnExists(DatabaseMetaData metaData, String table, String column) throws SQLException {
        String[] tableNames = {table, table.toLowerCase(), table.toUpperCase()};
        String[] columnNames = {column, column.toLowerCase(), column.toUpperCase()};
        for (String tableNameCandidate : tableNames) {
            for (String columnNameCandidate : columnNames) {
                try (ResultSet resultSet = metaData.getColumns(null, null, tableNameCandidate, columnNameCandidate)) {
                    if (resultSet.next()) {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    public static PlayerData getPlayerData(UUID uuid) {
        PlayerData bd = null;
        try {
            Connection connection = database.getConnectionAndCheck();
            String sql = "select * from " + tableName + " where UID = ?";
            if (XConomyLoad.Config.UUIDMODE.equals(UUIDMode.SEMIONLINE)) {
                String fallback = XConomyLoad.DConfig.isPostgreSQL() ? "COALESCE" : "ifnull";
                sql = "select * from " + tableName + " where UID = " + fallback
                        + "((select DUUID from " + tableUUIDName + " where UUID = ?), ?)";
            }
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setString(1, uuid.toString());
            if (XConomyLoad.Config.UUIDMODE.equals(UUIDMode.SEMIONLINE)) {
                statement.setString(2, uuid.toString());
            }

            ResultSet rs = statement.executeQuery();
            if (rs.next()) {
                UUID fuuid = uuid;
                if (XConomyLoad.Config.UUIDMODE.equals(UUIDMode.SEMIONLINE)) {
                    fuuid = UUID.fromString(rs.getString(1));
                    Cache.insertIntoMultiUUIDCache(fuuid, uuid);
                }
                BigDecimal cacheThisAmt = DataFormat.formatString(rs.getString(3));
                bd = new PlayerData(fuuid, rs.getString(2), cacheThisAmt);
                Cache.insertIntoCache(fuuid, bd);
                Cache.insertIntoHiddenMap(fuuid, rs.getInt(4));
            }

            rs.close();
            statement.close();
            database.closeHikariConnection(connection);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return bd;
    }

    @SuppressWarnings("ConstantConditions")
    public static PlayerData getPlayerData(String name) {
        PlayerData bd = null;
        try {
            Connection connection = database.getConnectionAndCheck();
            String query;

            if (XConomyLoad.Config.USERNAME_IGNORE_CASE) {
                if (XConomyLoad.DConfig.getStorageType() == 1) {
                    query = "select * from " + tableName + " where player = ? COLLATE NOCASE";
                } else if (XConomyLoad.DConfig.isPostgreSQL()) {
                    query = "select * from " + tableName + " where LOWER(player) = LOWER(?)";
                } else {
                    query = "select * from " + tableName + " where player = ?";
                }
            } else {
                if (XConomyLoad.DConfig.isMySQL()) {
                    query = "select * from " + tableName + " where binary player = ?";
                } else {
                    query = "select * from " + tableName + " where player = ?";
                }
            }

            PreparedStatement statement = connection.prepareStatement(query);
            statement.setString(1, name);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                UUID uuid = UUID.fromString(rs.getString(1));
                UUID puuid = null;
                if (XConomyLoad.Config.UUIDMODE.equals(UUIDMode.OFFLINE) || XConomyLoad.Config.UUIDMODE.equals(UUIDMode.ONLINE)) {
                    puuid = GetUUID.getUUID(null, name);
                }
                if (XConomyLoad.Config.UUIDMODE.equals(UUIDMode.DEFAULT) || XConomyLoad.Config.UUIDMODE.equals(UUIDMode.SEMIONLINE)
                        || (puuid != null && uuid.toString().equalsIgnoreCase(puuid.toString()))) {
                    String username = rs.getString(2);
                    BigDecimal cacheThisAmt = DataFormat.formatString(rs.getString(3));
                    if (cacheThisAmt != null) {
                        bd = new PlayerData(uuid, username, cacheThisAmt);
                        Cache.insertIntoCache(uuid, bd);
                        Cache.insertIntoHiddenMap(uuid, rs.getInt(4));
                    }
                    break;
                }
            }

            rs.close();
            statement.close();
            database.closeHikariConnection(connection);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return bd;
    }


    public static BigDecimal getNonPlayerData(String playerName) {
        BigDecimal bal = null;
        try {
            Connection connection = database.getConnectionAndCheck();
            String query;

            if (XConomyLoad.DConfig.isMySQL()) {
                query = "select * from " + tableNonPlayerName + " where binary account = ?";
            } else {
                query = "select * from " + tableNonPlayerName + " where account = ?";
            }

            PreparedStatement statement = connection.prepareStatement(query);
            statement.setString(1, playerName);

            ResultSet rs = statement.executeQuery();
            if (rs.next()) {
                bal = DataFormat.formatString(rs.getString("balance"));
                CacheNonPlayer.insertIntoCache(playerName, bal);
            }

            rs.close();
            statement.close();
            database.closeHikariConnection(connection);
            return bal;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public static BalanceMutationResult save(PlayerData pd, Boolean isAdd, BigDecimal amount, RecordInfo ri) {
        if (DataMigration.isRunning()) {
            return BalanceMutationResult.failure(BalanceMutationResult.Status.DATABASE_ERROR, pd.getBalance());
        }
        synchronized (WRITE_LOCK) {
            if (DataMigration.isRunning()) {
                return BalanceMutationResult.failure(BalanceMutationResult.Status.DATABASE_ERROR, pd.getBalance());
            }
            Connection connection = database.getConnectionAndCheck();
            if (connection == null) {
                return BalanceMutationResult.failure(BalanceMutationResult.Status.DATABASE_ERROR, pd.getBalance());
            }

            boolean previousAutoCommit = true;
            try {
                previousAutoCommit = connection.getAutoCommit();
                connection.setAutoCommit(false);

                String query = "update " + tableName + " set balance = ? where UID = ?";
                if (isAdd != null) {
                    if (isAdd) {
                        query = "update " + tableName
                                + " set balance = balance + ? where UID = ? and balance + ? <= ?";
                    } else {
                        query = "update " + tableName
                                + " set balance = balance - ? where UID = ? and balance >= ?";
                    }
                }

                int updated;
                try (PreparedStatement statement = connection.prepareStatement(query)) {
                    statement.setBigDecimal(1, amount);
                    statement.setString(2, pd.getUniqueId().toString());
                    if (isAdd != null) {
                        statement.setBigDecimal(3, amount);
                        if (isAdd) {
                            statement.setBigDecimal(4, DataFormat.maxNumber);
                        }
                    }
                    updated = statement.executeUpdate();
                }

                if (updated != 1) {
                    BigDecimal currentBalance = readBalance(connection, pd.getUniqueId());
                    connection.rollback();
                    if (currentBalance == null) {
                        return BalanceMutationResult.failure(BalanceMutationResult.Status.NOT_FOUND, pd.getBalance());
                    }
                    BalanceMutationResult.Status status = Boolean.FALSE.equals(isAdd)
                            ? BalanceMutationResult.Status.INSUFFICIENT_FUNDS
                            : BalanceMutationResult.Status.MAX_BALANCE;
                    return BalanceMutationResult.failure(status, currentBalance);
                }

                BigDecimal newBalance = readBalance(connection, pd.getUniqueId());
                if (newBalance == null) {
                    connection.rollback();
                    return BalanceMutationResult.failure(BalanceMutationResult.Status.NOT_FOUND, pd.getBalance());
                }

                PlayerData recordData = new PlayerData(pd.getUniqueId(), pd.getName(), newBalance);
                Long transactionId = recordStrict(connection, recordData, isAdd, amount, newBalance, ri,
                        ri.getFromUid(), ri.getToUid(), ri.getTransactionType());
                connection.commit();
                return BalanceMutationResult.success(newBalance, transactionId);
            } catch (SQLException e) {
                rollback(connection);
                e.printStackTrace();
                return BalanceMutationResult.failure(BalanceMutationResult.Status.DATABASE_ERROR, pd.getBalance());
            } finally {
                restoreAutoCommit(connection, previousAutoCommit);
                database.closeHikariConnection(connection);
            }
        }
    }

    public static BalanceTransferResult transfer(PlayerData sender, PlayerData target,
                                                 BigDecimal senderAmount, BigDecimal targetAmount,
                                                 RecordInfo senderRecord, RecordInfo targetRecord) {
        if (DataMigration.isRunning()) {
            return BalanceTransferResult.failure(BalanceMutationResult.Status.DATABASE_ERROR,
                    sender.getBalance(), target.getBalance());
        }
        synchronized (WRITE_LOCK) {
            if (DataMigration.isRunning()) {
                return BalanceTransferResult.failure(BalanceMutationResult.Status.DATABASE_ERROR,
                        sender.getBalance(), target.getBalance());
            }
            Connection connection = database.getConnectionAndCheck();
            if (connection == null) {
                return BalanceTransferResult.failure(BalanceMutationResult.Status.DATABASE_ERROR,
                        sender.getBalance(), target.getBalance());
            }

            boolean previousAutoCommit = true;
            try {
                previousAutoCommit = connection.getAutoCommit();
                connection.setAutoCommit(false);

                boolean senderFirst = sender.getUniqueId().toString()
                        .compareTo(target.getUniqueId().toString()) < 0;
                if (senderFirst) {
                    if (!withdraw(connection, sender.getUniqueId(), senderAmount)) {
                        return rollbackTransfer(connection, BalanceMutationResult.Status.INSUFFICIENT_FUNDS,
                                sender, target);
                    }
                    if (!deposit(connection, target.getUniqueId(), targetAmount)) {
                        return rollbackTransfer(connection, BalanceMutationResult.Status.MAX_BALANCE,
                                sender, target);
                    }
                } else {
                    if (!deposit(connection, target.getUniqueId(), targetAmount)) {
                        return rollbackTransfer(connection, BalanceMutationResult.Status.MAX_BALANCE,
                                sender, target);
                    }
                    if (!withdraw(connection, sender.getUniqueId(), senderAmount)) {
                        return rollbackTransfer(connection, BalanceMutationResult.Status.INSUFFICIENT_FUNDS,
                                sender, target);
                    }
                }

                BigDecimal senderBalance = readBalance(connection, sender.getUniqueId());
                BigDecimal targetBalance = readBalance(connection, target.getUniqueId());
                if (senderBalance == null || targetBalance == null) {
                    return rollbackTransfer(connection, BalanceMutationResult.Status.NOT_FOUND, sender, target);
                }

                PlayerData senderData = new PlayerData(sender.getUniqueId(), sender.getName(), senderBalance);
                PlayerData targetData = new PlayerData(target.getUniqueId(), target.getName(), targetBalance);
                Long senderTransactionId = recordStrict(connection, senderData, false, senderAmount, senderBalance,
                        senderRecord, senderRecord.getFromUid(), senderRecord.getToUid(),
                        senderRecord.getTransactionType());
                Long targetTransactionId = recordStrict(connection, targetData, true, targetAmount, targetBalance,
                        targetRecord, targetRecord.getFromUid(), targetRecord.getToUid(),
                        targetRecord.getTransactionType());

                connection.commit();
                return BalanceTransferResult.success(senderBalance, targetBalance,
                        senderTransactionId, targetTransactionId);
            } catch (SQLException e) {
                rollback(connection);
                e.printStackTrace();
                return BalanceTransferResult.failure(BalanceMutationResult.Status.DATABASE_ERROR,
                        sender.getBalance(), target.getBalance());
            } finally {
                restoreAutoCommit(connection, previousAutoCommit);
                database.closeHikariConnection(connection);
            }
        }
    }

    private static boolean withdraw(Connection connection, UUID uuid, BigDecimal amount) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(
                "update " + tableName + " set balance = balance - ? where UID = ? and balance >= ?")) {
            statement.setBigDecimal(1, amount);
            statement.setString(2, uuid.toString());
            statement.setBigDecimal(3, amount);
            return statement.executeUpdate() == 1;
        }
    }

    private static boolean deposit(Connection connection, UUID uuid, BigDecimal amount) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(
                "update " + tableName + " set balance = balance + ? where UID = ? and balance + ? <= ?")) {
            statement.setBigDecimal(1, amount);
            statement.setString(2, uuid.toString());
            statement.setBigDecimal(3, amount);
            statement.setBigDecimal(4, DataFormat.maxNumber);
            return statement.executeUpdate() == 1;
        }
    }

    private static BigDecimal readBalance(Connection connection, UUID uuid) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(
                "select balance from " + tableName + " where UID = ?")) {
            statement.setString(1, uuid.toString());
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    return resultSet.getBigDecimal(1);
                }
            }
        }
        return null;
    }

    private static BalanceTransferResult rollbackTransfer(Connection connection,
                                                          BalanceMutationResult.Status status,
                                                          PlayerData sender, PlayerData target)
            throws SQLException {
        connection.rollback();
        BigDecimal senderBalance = readBalance(connection, sender.getUniqueId());
        BigDecimal targetBalance = readBalance(connection, target.getUniqueId());
        return BalanceTransferResult.failure(status,
                senderBalance == null ? sender.getBalance() : senderBalance,
                targetBalance == null ? target.getBalance() : targetBalance);
    }

    private static void rollback(Connection connection) {
        try {
            connection.rollback();
        } catch (SQLException rollbackException) {
            rollbackException.printStackTrace();
        }
    }

    private static void restoreAutoCommit(Connection connection, boolean autoCommit) {
        try {
            connection.setAutoCommit(autoCommit);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    //public static void save(String type, PlayerData pd, Boolean isAdd,
    //                        BigDecimal oldbalance, BigDecimal amount, String command) {
    //    Connection connection = database.getConnectionAndCheck();
    //    UUID u = pd.getUniqueId();
    //    try {
    //        String query;
    //        query = " set balance = " + pd.getbalance().doubleValue() + " where UID = ?";
    //        boolean requirefresh = false;
    //        if (isAdd != null) {
    //            requirefresh = true;
    //            query = query + "AND balance = " + oldbalance.toString();
    //        }
    //        PreparedStatement statement1 = connection.prepareStatement("update " + tableName + query);
    //        statement1.setString(1, u.toString());
    //        int rs = statement1.executeUpdate();
    //        statement1.close();
    //        if (requirefresh && rs == 0) {
    //            command += "(Cache Correction)";
    //        }
    //        record(connection, type, pd, isAdd, amount, pd.getbalance(), command);
    //        if (requirefresh && rs == 0) {
    //            DataCon.refreshFromCache(u);
    //            PlayerData npd = DataCon.cachecorrection(u, amount, isAdd);
    //            if (isAdd) {
    //               query = " set balance = balance + " + amount.doubleValue() + " where UID = ?";
    //            } else {
    //                query = " set balance = balance - " + amount.doubleValue() + " where UID = ?";
    //            }
    //            PreparedStatement statement2 = connection.prepareStatement("update " + tableName + query);
    //            statement2.setString(1, u.toString());
    //            statement2.executeUpdate();
    //            statement2.close();
    //            record(connection, type, npd, isAdd, amount, npd.getbalance(), "Cache Correction Detail");
    //        }
    //    } catch (SQLException e) {
    //        e.printStackTrace();
    //    }
    //    database.closeHikariConnection(connection);
    //}

    public static void saveall(String targettype, List<UUID> players, BigDecimal amount, Boolean isAdd,
                               RecordInfo ri) {
        if (DataMigration.isRunning()) {
            return;
        }
        if (targettype.equalsIgnoreCase("online") && (players == null || players.isEmpty())) {
            return;
        }

        Connection connection = database.getConnectionAndCheck();
        try {
            String balanceUpdate;
            if (isAdd == null) {
                balanceUpdate = "balance = ?";
            } else if (isAdd) {
                balanceUpdate = "balance = balance + ?";
            } else {
                balanceUpdate = "balance = balance - ?";
            }

            if (targettype.equalsIgnoreCase("all")) {
                PreparedStatement statement = connection.prepareStatement(
                        "update " + tableName + " set " + balanceUpdate);
                statement.setBigDecimal(1, amount);
                statement.executeUpdate();
                statement.close();
            } else if (targettype.equalsIgnoreCase("online")) {
                String placeholders = String.join(", ", Collections.nCopies(players.size(), "?"));
                PreparedStatement statement = connection.prepareStatement(
                        "update " + tableName + " set " + balanceUpdate
                                + " where UID in (" + placeholders + ")");
                statement.setBigDecimal(1, amount);
                for (int i = 0; i < players.size(); i++) {
                    statement.setString(i + 2, players.get(i).toString());
                }
                statement.executeUpdate();
                statement.close();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        if (ri != null) {
            record(connection, null, isAdd, amount, BigDecimal.ZERO, ri);
        }
        database.closeHikariConnection(connection);
    }

    public static void saveNonPlayer(String account, BigDecimal amount,
                                     BigDecimal newbalance, Boolean isAdd, RecordInfo ri) {
        if (DataMigration.isRunning()) {
            return;
        }
        Connection connection = database.getConnectionAndCheck();
        try {
            String query = " set balance = ? where account = ?";
            if (XConomyLoad.Config.DISABLE_CACHE) {
                if (isAdd != null) {
                    if (isAdd) {
                        query = " set balance = balance + ? where account = ?";
                    } else {
                        query = " set balance = balance - ? where account = ?";
                    }
                }
            }
            PreparedStatement statement = connection.prepareStatement("update " + tableNonPlayerName + query);
            if (!XConomyLoad.Config.DISABLE_CACHE) {
                statement.setDouble(1, newbalance.doubleValue());
            } else {
                statement.setDouble(1, amount.doubleValue());
            }
            statement.setString(2, account);
            statement.executeUpdate();
            statement.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        record(connection, new PlayerData(null, account, null), isAdd, amount, newbalance, ri, ri.getFromUid(), ri.getToUid(), ri.getTransactionType());
        database.closeHikariConnection(connection);
    }


    public static void deletePlayerData(String UUID) {
        if (DataMigration.isRunning()) {
            return;
        }
        Connection connection = database.getConnectionAndCheck();
        try {
            String query = "delete from " + tableName + " where UID = ?";
            PreparedStatement statement = connection.prepareStatement(query);
            statement.setString(1, UUID);
            statement.executeUpdate();
            statement.close();
            if (XConomyLoad.Config.UUIDMODE.equals(UUIDMode.SEMIONLINE)) {
                query = "delete from " + tableUUIDName + " where DUUID = ?";
                statement = connection.prepareStatement(query);
                statement.setString(1, UUID);
                statement.executeUpdate();
                statement.close();
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
        database.closeHikariConnection(connection);
    }

    public static void getBaltop() {
        try {
            Connection connection = database.getConnectionAndCheck();
            PreparedStatement statement = connection.prepareStatement(
                    "select * from " + tableName + " where hidden != '1' order by balance desc limit " + XConomyLoad.Config.RANKING_SIZE);

            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                Cache.baltop.put(rs.getString(2), DataFormat.formatString(rs.getString(3)));
                Cache.baltop_papi.add(rs.getString(2));
            }

            rs.close();
            statement.close();
            database.closeHikariConnection(connection);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public static String sumBal() {
        String bal = "0.0";

        try {
            Connection connection = database.getConnectionAndCheck();
            PreparedStatement statement = connection.prepareStatement("select SUM(balance) from " + tableName + " where hidden != '1'");

            ResultSet rs = statement.executeQuery();
            if (rs.next()) {
                bal = rs.getString(1);
            }

            rs.close();
            statement.close();
            database.closeHikariConnection(connection);
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return bal;
    }

    public static void hidetop(UUID u, int type) {
        Connection connection = database.getConnectionAndCheck();
        try {
            String query = " set hidden = ? where UID = ?";
            PreparedStatement statement = connection.prepareStatement("update " + tableName + query);
            statement.setInt(1, type);
            statement.setString(2, u.toString());
            statement.executeUpdate();
            statement.close();
            Cache.insertIntoHiddenMap(u, type);

        } catch (SQLException e) {
            e.printStackTrace();
        }
        database.closeHikariConnection(connection);
    }

    public static Long record(Connection co, PlayerData pd, Boolean isAdd,
                              BigDecimal amount, BigDecimal newbalance, RecordInfo ri) {
        return record(co, pd, isAdd, amount, newbalance, ri, null, null, null);
    }

    public static Long record(Connection co, PlayerData pd, Boolean isAdd,
                              BigDecimal amount, BigDecimal newbalance, RecordInfo ri,
                              UUID fromUid, UUID toUid, String transactionType) {
        try {
            return recordStrict(co, pd, isAdd, amount, newbalance, ri, fromUid, toUid, transactionType);
        } catch (SQLException e) {
            e.printStackTrace();
            return null;
        }
    }

    private static Long recordStrict(Connection co, PlayerData pd, Boolean isAdd,
                                     BigDecimal amount, BigDecimal newbalance, RecordInfo ri,
                                     UUID fromUid, UUID toUid, String transactionType) throws SQLException {
        if (!XConomyLoad.DConfig.isRemoteDatabase() || !XConomyLoad.Config.TRANSACTION_RECORD) {
            return null;
        }
        String uid = pd != null && pd.getUniqueId() != null ? pd.getUniqueId().toString() : "N/A";
        String name = pd != null ? pd.getName() : "N/A";
        String operation = isAdd == null ? "SET" : (isAdd ? "DEPOSIT" : "WITHDRAW");
        Timestamp timestamp = new Timestamp(new Date().getTime());

        if (XConomyLoad.isTransactionTrackingEnabled()) {
            String query = "INSERT INTO " + tableRecordName
                    + "(type,uid,player,balance,amount,operation,command,comment,datetime,from_uid,to_uid,"
                    + "transaction_type,server_id,trace_id,parent_transaction_id) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            try (PreparedStatement statement = co.prepareStatement(query, PreparedStatement.RETURN_GENERATED_KEYS)) {
                statement.setString(1, ri.getType());
                statement.setString(2, uid);
                statement.setString(3, name);
                statement.setBigDecimal(4, newbalance);
                statement.setBigDecimal(5, amount);
                statement.setString(6, operation);
                statement.setString(7, ri.getCommand());
                statement.setString(8, ri.getComment());
                statement.setTimestamp(9, timestamp);
                statement.setString(10, fromUid != null ? fromUid.toString() : "N/A");
                statement.setString(11, toUid != null ? toUid.toString() : "N/A");
                statement.setString(12, transactionType != null ? transactionType : "UNKNOWN");
                statement.setString(13, XConomyLoad.Config.SYNCDATA_SIGN);
                statement.setString(14, ri.getTraceId());
                if (ri.getParentTransactionId() != null) {
                    statement.setLong(15, ri.getParentTransactionId());
                } else {
                    statement.setNull(15, Types.BIGINT);
                }
                statement.executeUpdate();
                try (ResultSet generatedKeys = statement.getGeneratedKeys()) {
                    return generatedKeys.next() ? generatedKeys.getLong(1) : null;
                }
            }
        }

        String query = "INSERT INTO " + tableRecordName
                + "(type,uid,player,balance,amount,operation,command,comment,datetime) values(?,?,?,?,?,?,?,?,?)";
        try (PreparedStatement statement = co.prepareStatement(query)) {
            statement.setString(1, ri.getType());
            statement.setString(2, uid);
            statement.setString(3, name);
            statement.setBigDecimal(4, newbalance);
            statement.setBigDecimal(5, amount);
            statement.setString(6, operation);
            statement.setString(7, ri.getCommand());
            statement.setString(8, ri.getComment());
            statement.setTimestamp(9, timestamp);
            statement.executeUpdate();
        }
        return null;
    }

}
